name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-firebase:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo -e "@madnesslabs:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_PAT }}" > ~/.npmrc
      - name: Install Dependencies
        run: npm install --verbose --unsafe-perm
      - name: Deploy to Firebase
        run: npm run deploy:firebase -- --token "${{ secrets.FIREBASE_TOKEN }}"
  deploy-graphql:
    name: Deploy GraphQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - run: echo -e "@madnesslabs:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_PAT }}" > ~/.npmrc
      - name: Install Dependencies
        run: npm install --verbose --unsafe-perm
      - name: Build
        run: npm run build
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml
